### PR TITLE
Added OneDark Rofi Theme

### PR DESCRIPTION
**Pull request by KILLinefficiency**
Hello @Murzchnvok !

I added a OneDark based Rofi Theme.

my_rofi

The selected item is highlighted with green.
* Font: [JetBrains Mono](https://archlinux.org/packages/community/any/ttf-jetbrains-mono/)
*  Icons: [Papirus](https://archlinux.org/packages/community/any/papirus-icon-theme/)

I hope you like it!
Also, I'd appreciate it if you could add a ``hacktoberfest-accepted`` tag to this Pull Request. :smile: 

Kind Regards,
Shreyas

### CODE REVIEW

**Comment by Murzchnvok** [comment]
Hello, thank you!

**Comment by KILLinefficiency** [comment]
@Murzchnvok Could you please add ``hacktoberfest-accepted`` tag to this PR?

**Comment by Murzchnvok** [comment]
I can't, PR doesn't accept tags. But I added to the repo, even tho I'm not sure why.

**Comment by Murzchnvok** [comment]
Of course ;-)

**Comment by KILLinefficiency** [comment]
@Murzchnvok Thank You for this!

**Pull request merged**
